name: Full CI workflow for final checks

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      package:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true
      ACCESS_TOKEN:
        required: true

jobs:

  build:
    runs-on: ${{ inputs.os }}

    name: Full Test Suite ${{ inputs.os }} (${{ inputs.python-version }})

    steps:
    - uses: actions/checkout@v4
    - name: Configure secret access
      run: |
        git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github
    - name: Cache conda
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache if environment.yaml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yaml') }}-${{ inputs.python-version }}
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ inputs.python-version }}
        environment-file: environment.yaml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: Install package
      shell: bash -l {0}
      run: |
        pip install .
    - name: Analysing the code with pylint
      shell: bash -l {0}
      run: |
        pylint --rcfile=.pylintrc ${{ inputs.package }} tests
    - name: Sphinx Build
      shell: bash -l {0}
      run: |
        cd docs
        make clean
        make html
    - name: Test Suite with Coverage
      shell: bash -l {0}
      run: |
        python -m pytest --cache-clear --cov=${{ inputs.package }} --cov-report=xml tests
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
