name: Quick CI workflow for in-progress work

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      package:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:

  build:
    runs-on: ${{ inputs.os }}

    name: Quick Check ${{ inputs.os }} (${{ inputs.python-version }})

    steps:
    - uses: actions/checkout@v2
    - name: Configure secret access
      run: |
        git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if environment.yaml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yaml') }}-${{ inputs.python-version }}
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ inputs.python-version }}
        environment-file: environment.yaml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: Install package
      shell: bash -l {0}
      run: |
        pip install .
    - name: Analysing the code with pylint
      shell: bash -l {0}
      run: |
        pylint --rcfile=.pylintrc ${{ inputs.package }} tests
    - name: Test Suite
      shell: bash -l {0}
      run: |
        python -m pytest tests
