name: Python Package CI Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string

jobs:

  build:
    runs-on: ${{ inputs.os }}

    name: ${{ inputs.os }} (${{ inputs.python-version }})

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Check for editable install
      run: pip install -e .

  testing:
    needs: build
    name: PyTest based on Python ${{ inputs.python-version }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v2
        with:
         python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install .[tests]
      - name: Check for editable install
        run: pip install -e .
      - name: Run test suite
        run: |
          python -m pytest tests

  coverage:
    needs: testing
    name: Coverage calculations based on Python ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v2
        with:
         python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install .[tests]
      - name: Run tests
        run: |
          python -m pytest --cache-clear --cov=erap --cov-report=xml tests
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  linting:
    needs: build
    name: Lint based on Python ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .[tests]
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc erap tests

  sphinx:
    needs: build
    name: Build Sphinx Docs based on Python ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[docs]
    - name: Sphinx Build
      run: |
        cd docs
        make clean
        make html
