# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: Lintr for projects

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  lint-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure secret access
        run: |
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install lintr
        run: |
          install.packages("remotes")
          remotes::install_github('r-lib/lintr')
        shell: Rscript {0}

      - name: Lint root directory
        run: lintr::lint_dir(exclusions = list("renv",".venv"))
        shell: Rscript {0}
