name: Release Bump

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  czbump:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Throw deprecation error
        run: |
          echo "This workflow is deprecated. Please use the one in infrastructure."
          exit 1
