name: Staleness Tagger

on: workflow_call

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v5.0.0
        with:
          days-before-stale: 7
          days-before-close: 7
          stale-issue-message: 'This issue is stale and will be closed in 7 days.'
          stale-pr-message: 'This PR is stale. Please approve, update, or request changes.'
