name: Staleness Tagger

on: workflow_call

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Throw deprecation error
        run: |
          echo "This workflow is deprecated. Please use the one in infrastructure."
          exit 1
